const { PrismaClient } = require("@prisma/client");
const database = new PrismaClient();

const leetCodeProblems = [
  // Starting with LeetCode 75
  {
    title: "Merge Strings Alternately",
    href: "https://leetcode.com/problems/merge-strings-alternately/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Two Pointers" },
      { tag: "String" },
    ],
  },
  {
    title: "Greatest Common Divisor of Strings",
    href: "https://leetcode.com/problems/greatest-common-divisor-of-strings/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Math" },
      { tag: "String" },
    ],
  },
  {
    title: "Kids With the Greatest Number of Candies",
    href: "https://leetcode.com/problems/kids-with-the-greatest-number-of-candies/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
    ],
  },
  {
    title: "Can Place Flowers",
    href: "https://leetcode.com/problems/can-place-flowers/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Greedy" },
    ],
  },
  {
    title: "Reverse Vowels of a String",
    href: "https://leetcode.com/problems/reverse-vowels-of-a-string/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Two Pointers" },
      { tag: "String" },
    ],
  },
  {
    title: "Reverse Words in a String",
    href: "https://leetcode.com/problems/reverse-words-in-a-string/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Two Pointers" },
      { tag: "String" },
    ],
  },
  {
    title: "Product of Array Except Self",
    href: "https://leetcode.com/problems/product-of-array-except-self/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Prefix Sum" },
    ],
  },
  {
    title: "Increasing Triplet Subsequence",
    href: "https://leetcode.com/problems/increasing-triplet-subsequence/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Greedy" },
    ],
  },
  {
    title: "String Compression",
    href: "https://leetcode.com/problems/string-compression/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Two Pointers" },
      { tag: "String" },
    ],
  },
  {
    title: "Move Zeroes",
    href: "https://leetcode.com/problems/move-zeroes/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Two Pointers" },
    ],
  },
  {
    title: "Is Subsequence",
    href: "https://leetcode.com/problems/is-subsequence/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Two Pointers" },
      { tag: "String" },
      { tag: "Dynamic Programming" },
    ],
  },
  {
    title: "Container With Most Water",
    href: "https://leetcode.com/problems/container-with-most-water/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Two Pointers" },
      { tag: "Greedy" },
    ],
  },
  {
    title: "Max Number of K-Sum Pairs",
    href: "https://leetcode.com/problems/max-number-of-k-sum-pairs/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Table" },
      { tag: "Two Pointers" },
      { tag: "Sorting" },
    ],
  },
  {
    title: "Maximum Average Subarray I",
    href: "https://leetcode.com/problems/maximum-average-subarray-i/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Sliding Window" },
    ],
  },
  {
    title: "Maximum Number of Vowels in a Substring of Given Length",
    href: "https://leetcode.com/problems/maximum-number-of-vowels-in-a-substring-of-given-length/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "String" },
      { tag: "Sliding Window" },
    ],
  },
  {
    title: "Max Consecutive Ones III",
    href: "https://leetcode.com/problems/max-consecutive-ones-iii/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Binary Search" },
      { tag: "Sliding Window" },
      { tag: "Prefix Sum" },
    ],
  },
  {
    title: "Longest Subarray of 1's After Deleting One Element",
    href: "https://leetcode.com/problems/longest-subarray-of-1s-after-deleting-one-element/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Dynamic Programming" },
      { tag: "Sliding Window" },
    ],
  },
  {
    title: "Find the Highest Altitude",
    href: "https://leetcode.com/problems/find-the-highest-altitude/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Prefix Sum" },
    ],
  },
  {
    title: "Find Pivot Index",
    href: "https://leetcode.com/problems/find-pivot-index/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Prefix Sum" },
    ],
  },
  {
    title: "Find the Difference of Two Arrays",
    href: "https://leetcode.com/problems/find-the-difference-of-two-arrays/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Table" },
    ],
  },
  {
    title: "Unique Number of Occurrences",
    href: "https://leetcode.com/problems/unique-number-of-occurrences/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Table" },
    ],
  },
  {
    title: "Determine if Two Strings Are Close",
    href: "https://leetcode.com/problems/determine-if-two-strings-are-close/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Hash Table" },
      { tag: "String" },
      { tag: "Sorting" },
      { tag: "Counting" },
    ],
  },
  {
    title: "Equal Row and Column Pairs",
    href: "https://leetcode.com/problems/equal-row-and-column-pairs/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Table" },
      { tag: "Matrix" },
      { tag: "Simulation" },
    ],
  },
  {
    title: "Removing Stars From a String",
    href: "https://leetcode.com/problems/removing-stars-from-a-string/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "String" },
      { tag: "Stack" },
      { tag: "Simulation" },
    ],
  },
  {
    title: "Asteroid Collision",
    href: "https://leetcode.com/problems/asteroid-collision/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Stack" },
      { tag: "Simulation" },
    ],
  },
  {
    title: "Decode String",
    href: "https://leetcode.com/problems/decode-string/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "String" },
      { tag: "Stack" },
      { tag: "Recursion" },
    ],
  },
  {
    title: "Number of Recent Calls",
    href: "https://leetcode.com/problems/number-of-recent-calls/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Design" },
      { tag: "Queue" },
      { tag: "Data Stream" },
    ],
  },
  {
    title: "Dota2 Senate",
    href: "https://leetcode.com/problems/dota2-senate/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "String" },
      { tag: "Greedy" },
      { tag: "Queue" },
    ],
  },
  {
    title: "Delete the Middle Node of a Linked List",
    href: "https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Linked List" },
      { tag: "Two Pointers" },
    ],
  },
  {
    title: "Odd Even Linked List",
    href: "https://leetcode.com/problems/odd-even-linked-list/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Linked List" },
    ],
  },
  {
    title: "Reverse Linked List",
    href: "https://leetcode.com/problems/reverse-linked-list/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Linked List" },
      { tag: "Recursion" },
    ],
  },
  {
    title: "Maximum Twin Sum of a Linked List",
    href: "https://leetcode.com/problems/maximum-twin-sum-of-a-linked-list/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Linked List" },
      { tag: "Two Pointers" },
      { tag: "Stack" },
    ],
  },
  {
    title: "Maximum Depth of Binary Tree",
    href: "https://leetcode.com/problems/maximum-depth-of-binary-tree/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Binary Tree" },
    ],
  },
  {
    title: "Leaf-Similar Trees",
    href: "https://leetcode.com/problems/leaf-similar-trees/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Binary Tree" },
    ],
  },
  {
    title: "Count Good Nodes in Binary Tree",
    href: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Binary Tree" },
    ],
  },
  {
    title: "Path Sum III",
    href: "https://leetcode.com/problems/path-sum-iii/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Binary Tree" },
    ],
  },
  {
    title: "Longest ZigZag Path in a Binary Tree",
    href: "https://leetcode.com/problems/longest-zigzag-path-in-a-binary-tree/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Dynamic Programming" },
      { tag: "Depth-First Search" },
      { tag: "Binary Tree" },
    ],
  },
  {
    title: "Lowest Common Ancestor of a Binary Tree",
    href: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Binary Tree" },
    ],
  },
  {
    title: "Binary Tree Right Side View",
    href: "https://leetcode.com/problems/binary-tree-right-side-view/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Binary Tree" },
    ],
  },
  {
    title: "Maximum Level Sum of a Binary Tree",
    href: "https://leetcode.com/problems/maximum-level-sum-of-a-binary-tree/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Binary Tree" },
    ],
  },
  {
    title: "Search in a Binary Search Tree",
    href: "https://leetcode.com/problems/search-in-a-binary-search-tree/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Binary Search Tree" },
      { tag: "Binary Tree" },
    ],
  },
  {
    title: "Delete Node in a BST",
    href: "https://leetcode.com/problems/delete-node-in-a-bst/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Binary Search Tree" },
      { tag: "Binary Tree" },
    ],
  },
  {
    title: "Keys and Rooms",
    href: "https://leetcode.com/problems/keys-and-rooms/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Graph" },
    ],
  },
  {
    title: "Number of Provinces",
    href: "https://leetcode.com/problems/number-of-provinces/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Union Find" },
      { tag: "Graph" },
    ],
  },
  {
    title: "Reorder Routes to Make All Paths Lead to the City Zero",
    href: "https://leetcode.com/problems/reorder-routes-to-make-all-paths-lead-to-the-city-zero/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Graph" },
    ],
  },
  {
    title: "Evaluate Division",
    href: "https://leetcode.com/problems/evaluate-division/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Graph" },
    ],
  },
  {
    title: "Nearest Exit from Entrance in Maze",
    href: "https://leetcode.com/problems/nearest-exit-from-entrance-in-maze/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Breadth-First Search" },
      { tag: "Matrix" },
    ],
  },
  {
    title: "Rotting Oranges",
    href: "https://leetcode.com/problems/rotting-oranges/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Breadth-First Search" },
      { tag: "Matrix" },
    ],
  },
  {
    title: "Kth Largest Element in an Array",
    href: "https://leetcode.com/problems/kth-largest-element-in-an-array/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Heap" },
      { tag: "Divide and Conquer" },
      { tag: "Sorting" },
    ],
  },
  {
    title: "Smallest Number in Infinite Set",
    href: "https://leetcode.com/problems/smallest-number-in-infinite-set/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Hash Table" },
      { tag: "Design" },
      { tag: "Heap" },
    ],
  },
  {
    title: "Maximum Subsequence Score",
    href: "https://leetcode.com/problems/maximum-subsequence-score/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Greedy" },
      { tag: "Sorting" },
      { tag: "Heap" },
    ],
  },
  {
    title: "Total Cost to Hire K Workers",
    href: "https://leetcode.com/problems/total-cost-to-hire-k-workers/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Two Pointers" },
      { tag: "Heap" },
    ],
  },
  {
    title: "Guess Number Higher or Lower",
    href: "https://leetcode.com/problems/guess-number-higher-or-lower/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Binary Search" },
      { tag: "Interactive" },
    ],
  },
  {
    title: "Successful Pairs of Spells and Potions",
    href: "https://leetcode.com/problems/successful-pairs-of-spells-and-potions/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Two Pointers" },
      { tag: "Binary Search" },
      { tag: "Sorting" },
    ],
  },
  {
    title: "Find Peak Element",
    href: "https://leetcode.com/problems/find-peak-element/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Binary Search" },
    ],
  },
  {
    title: "Koko Eating Bananas",
    href: "https://leetcode.com/problems/koko-eating-bananas/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Binary Search" },
    ],
  },
  {
    title: "Letter Combinations of a Phone Number",
    href: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Hash Table" },
      { tag: "String" },
      { tag: "Backtracking" },
    ],
  },
  {
    title: "Combination Sum III",
    href: "https://leetcode.com/problems/combination-sum-iii/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Backtracking" },
    ],
  },
  {
    title: "N-th Tribonacci Number",
    href: "https://leetcode.com/problems/n-th-tribonacci-number/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Math" },
      { tag: "Dynamic Programming" },
      { tag: "Memoization" },
    ],
  },
  {
    title: "Min Cost Climbing Stairs",
    href: "https://leetcode.com/problems/min-cost-climbing-stairs/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Dynamic Programming" },
    ],
  },
  {
    title: "House Robber",
    href: "https://leetcode.com/problems/house-robber/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Dynamic Programming" },
    ],
  },
  {
    title: "Domino and Tromino Tiling",
    href: "https://leetcode.com/problems/domino-and-tromino-tiling/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Dynamic Programming" },
    ],
  },
  {
    title: "Unique Paths",
    href: "https://leetcode.com/problems/unique-paths/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Math" },
      { tag: "Dynamic Programming" },
      { tag: "Combinatorics" },
    ],
  },
  {
    title: "Longest Common Subsequence",
    href: "https://leetcode.com/problems/longest-common-subsequence/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "String" },
      { tag: "Dynamic Programming" },
    ],
  },
  {
    title: "Best Time to Buy and Sell Stock with Transaction Fee",
    href: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Dynamic Programming" },
      { tag: "Greedy" },
    ],
  },
  {
    title: "Edit Distance",
    href: "https://leetcode.com/problems/edit-distance/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "String" },
      { tag: "Dynamic Programming" },
    ],
  },
  {
    title: "Counting Bits",
    href: "https://leetcode.com/problems/counting-bits/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Dynamic Programming" },
      { tag: "Bit Manipulation" },
    ],
  },
  {
    title: "Single Number",
    href: "https://leetcode.com/problems/single-number/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Bit Manipulation" },
    ],
  },
  {
    title: "Minimum Flips to Make a OR b Equal to c",
    href: "https://leetcode.com/problems/minimum-flips-to-make-a-or-b-equal-to-c/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Bit Manipulation" },
    ],
  },
  {
    title: "Implement Trie (Prefix Tree)",
    href: "https://leetcode.com/problems/implement-trie-prefix-tree/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Hash Table" },
      { tag: "String" },
      { tag: "Design" },
      { tag: "Trie" },
    ],
  },
  {
    title: "Search Suggestions System",
    href: "https://leetcode.com/problems/search-suggestions-system/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Heap" },
      { tag: "String" },
      { tag: "Binary Search" },
      { tag: "Trie" },
    ],
  },
  {
    title: "Non-overlapping Intervals",
    href: "https://leetcode.com/problems/non-overlapping-intervals/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Dynamic Programming" },
      { tag: "Greedy" },
      { tag: "Sorting" },
    ],
  },
  {
    title: "Minimum Number of Arrows to Burst Balloons",
    href: "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Greedy" },
      { tag: "Sorting" },
    ],
  },
  {
    title: "Daily Temperatures",
    href: "https://leetcode.com/problems/daily-temperatures/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Stack" },
      { tag: "Monotonic Stack" },
    ],
  },
  {
    title: "Online Stock Span",
    href: "https://leetcode.com/problems/online-stock-span/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Stack" },
      { tag: "Design" },
      { tag: "Monotonic Stack" },
    ],
  },
  // 75 problems end here ^^^

  {
    title: "Contains Duplicate",
    href: "https://leetcode.com/problems/contains-duplicate/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Table" },
      { tag: "Sorting" },
    ],
  },
  {
    title: "Valid Anagram",
    href: "https://leetcode.com/problems/valid-anagram/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Hash Table" },
      { tag: "String" },
      { tag: "Sorting" },
    ],
  },
  {
    title: "Two Sum",
    href: "https://leetcode.com/problems/two-sum/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Table" },
    ],
  },
  {
    title: "Group Anagrams",
    href: "https://leetcode.com/problems/group-anagrams/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Table" },
      { tag: "String" },
      { tag: "Sorting" },
    ],
  },
  {
    title: "Top K Frequent Elements",
    href: "https://leetcode.com/problems/top-k-frequent-elements/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Table" },
      { tag: "Heap" },
      { tag: "Sorting" },
    ],
  },
  {
    title: "Encode and Decode Strings",
    href: "https://leetcode.com/problems/encode-and-decode-strings/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Design" },
      { tag: "String" },
    ],
  },
  {
    title: "Longest Consecutive Sequence",
    href: "https://leetcode.com/problems/longest-consecutive-sequence/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Table" },
      { tag: "Union Find" },
    ],
  },
  {
    title: "Valid Palindrome",
    href: "https://leetcode.com/problems/valid-palindrome/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Two Pointers" },
      { tag: "String" },
    ],
  },
  {
    title: "3Sum",
    href: "https://leetcode.com/problems/3sum/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Two Pointers" },
      { tag: "Sorting" },
    ],
  },
  {
    title: "Best Time to Buy And Sell Stock",
    href: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Dynamic Programming" },
    ],
  },
  {
    title: "Longest Substring Without Repeating Characters",
    href: "https://leetcode.com/problems/longest-substring-without-repeating-characters/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Hash Table" },
      { tag: "String" },
      { tag: "Sliding Window" },
    ],
  },
  {
    title: "Longest Repeating Character Replacement",
    href: "https://leetcode.com/problems/longest-repeating-character-replacement/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Hash Table" },
      { tag: "String" },
      { tag: "Sliding Window" },
    ],
  },
  {
    title: "Minimum Window Substring",
    href: "https://leetcode.com/problems/minimum-window-substring/description/",
    difficulty: "Hard",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Hash Table" },
      { tag: "String" },
      { tag: "Sliding Window" },
    ],
  },
  {
    title: "Valid Parentheses",
    href: "https://leetcode.com/problems/valid-parentheses/description/",
    difficulty: "Easy",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "String" },
      { tag: "Stack" },
    ],
  },
  {
    title: "Find Minimum in Rotated Sorted Array",
    href: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Binary Search" },
    ],
  },
  {
    title: "Search in Rotated Sorted Array",
    href: "https://leetcode.com/problems/search-in-rotated-sorted-array/description/",
    difficulty: "Medium",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Binary Search" },
    ],
  },
  {
    title: "Minimum Window Substring",
    href: "https://leetcode.com/problems/minimum-window-substring/description/",
    difficulty: "Hard",
    completed: false,
    masteryLevel: "Practicing",
    notes: "",
    videoURL: "",
    tags: [
      { tag: "Hash Table" },
      { tag: "String" },
      { tag: "Sliding Window" },
    ],
  },
];

async function seedLeetCodeProblems() {
  await database.leetCodeProblem.deleteMany({});
  await database.problemTag.deleteMany({});

  for (const problem of leetCodeProblems) {
    const tags = problem.tags.map(tag => ({
      where: { tag: tag.tag },
      create: { tag: tag.tag },
    }));

    await database.leetCodeProblem.create({
      data: {
        title: problem.title,
        href: problem.href,
        difficulty: problem.difficulty,
        completed: problem.completed,
        masteryLevel: problem.masteryLevel,
        notes: problem.notes,
        videoURL: problem.videoURL,
        tags: {
          connectOrCreate: tags,
        },
      },
    });
  }

  console.log(`${leetCodeProblems.length} LeetCode problems have been inserted.`);
}

seedLeetCodeProblems()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await database.$disconnect();
  });

