const { PrismaClient } = require("@prisma/client");
const database = new PrismaClient();

const leetCodeProblems = [
  // Starting with LeetCode 75
  {
    id: 1,
    title: "Merge Strings Alternately",
    href: "https://leetcode.com/problems/merge-strings-alternately/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Two Pointers" },
      { tag: "String" },
    ],
  },
  {
    id: 2,
    title: "Greatest Common Divisor of Strings",
    href: "https://leetcode.com/problems/greatest-common-divisor-of-strings/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Math" },
      { tag: "String" },
    ],
  },
  {
    id: 3,
    title: "Kids With the Greatest Number of Candies",
    href: "https://leetcode.com/problems/kids-with-the-greatest-number-of-candies/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Array" },
    ],
  },
  {
    id: 4,
    title: "Can Place Flowers",
    href: "https://leetcode.com/problems/can-place-flowers/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Greedy" },
    ],
  },
  {
    id: 5,
    title: "Reverse Vowels of a String",
    href: "https://leetcode.com/problems/reverse-vowels-of-a-string/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Two Pointers" },
      { tag: "String" },
    ],
  },
  {
    id: 6,
    title: "Reverse Words in a String",
    href: "https://leetcode.com/problems/reverse-words-in-a-string/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Two Pointers" },
      { tag: "String" },
    ],
  },
  {
    id: 7,
    title: "Product of Array Except Self",
    href: "https://leetcode.com/problems/product-of-array-except-self/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Prefix Sum" },
    ],
  },
  {
    id: 8,
    title: "Increasing Triplet Subsequence",
    href: "https://leetcode.com/problems/increasing-triplet-subsequence/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Greedy" },
    ],
  },
  {
    id: 9,
    title: "String Compression",
    href: "https://leetcode.com/problems/string-compression/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Two Pointers" },
      { tag: "String" },
    ],
  },
  {
    id: 10,
    title: "Move Zeroes",
    href: "https://leetcode.com/problems/move-zeroes/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Two Pointers" },
    ],
  },
  {
    id: 11,
    title: "Is Subsequence",
    href: "https://leetcode.com/problems/is-subsequence/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Two Pointers" },
      { tag: "String" },
      { tag: "Dynamic Programming" },
    ],
  },
  {
    id: 12,
    title: "Container With Most Water",
    href: "https://leetcode.com/problems/container-with-most-water/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Two Pointers" },
      { tag: "Greedy" },
    ],
  },
  {
    id: 13,
    title: "Max Number of K-Sum Pairs",
    href: "https://leetcode.com/problems/max-number-of-k-sum-pairs/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Map" },
      { tag: "Two Pointers" },
      { tag: "Sorting" },
    ],
  },
  {
    id: 14,
    title: "Maximum Average Subarray I",
    href: "https://leetcode.com/problems/maximum-average-subarray-i/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Sliding Window" },
    ],
  },
  {
    id: 15,
    title: "Maximum Number of Vowels in a Substring of Given Length",
    href: "https://leetcode.com/problems/maximum-number-of-vowels-in-a-substring-of-given-length/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "String" },
      { tag: "Sliding Window" },
    ],
  },
  {
    id: 16,
    title: "Max Consecutive Ones III",
    href: "https://leetcode.com/problems/max-consecutive-ones-iii/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Binary Search" },
      { tag: "Sliding Window" },
      { tag: "Prefix Sum" },
    ],
  },
  {
    id: 17,
    title: "Longest Subarray of 1's After Deleting One Element",
    href: "https://leetcode.com/problems/longest-subarray-of-1s-after-deleting-one-element/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Dynamic Programming" },
      { tag: "Sliding Window" },
    ],
  },
  {
    id: 18,
    title: "Find the Highest Altitude",
    href: "https://leetcode.com/problems/find-the-highest-altitude/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Prefix Sum" },
    ],
  },
  {
    id: 19,
    title: "Find Pivot Index",
    href: "https://leetcode.com/problems/find-pivot-index/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Prefix Sum" },
    ],
  },
  {
    id: 20,
    title: "Find the Difference of Two Arrays",
    href: "https://leetcode.com/problems/find-the-difference-of-two-arrays/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Map" },
    ],
  },
  {
    id: 21,
    title: "Unique Number of Occurrences",
    href: "https://leetcode.com/problems/unique-number-of-occurrences/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Map" },
    ],
  },
  {
    id: 22,
    title: "Determine if Two Strings Are Close",
    href: "https://leetcode.com/problems/determine-if-two-strings-are-close/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Hash Map" },
      { tag: "String" },
      { tag: "Sorting" },
      { tag: "Counting" },
    ],
  },
  {
    id: 23,
    title: "Equal Row and Column Pairs",
    href: "https://leetcode.com/problems/equal-row-and-column-pairs/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Map" },
      { tag: "Matrix" },
      { tag: "Simulation" },
    ],
  },
  {
    id: 24,
    title: "Removing Stars From a String",
    href: "https://leetcode.com/problems/removing-stars-from-a-string/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "String" },
      { tag: "Stack" },
      { tag: "Simulation" },
    ],
  },
  {
    id: 25,
    title: "Asteroid Collision",
    href: "https://leetcode.com/problems/asteroid-collision/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Stack" },
      { tag: "Simulation" },
    ],
  },
  {
    id: 26,
    title: "Decode String",
    href: "https://leetcode.com/problems/decode-string/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "String" },
      { tag: "Stack" },
      { tag: "Recursion" },
    ],
  },
  {
    id: 27,
    title: "Number of Recent Calls",
    href: "https://leetcode.com/problems/number-of-recent-calls/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Design" },
      { tag: "Queue" },
      { tag: "Data Stream" },
    ],
  },
  {
    id: 28,
    title: "Dota2 Senate",
    href: "https://leetcode.com/problems/dota2-senate/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "String" },
      { tag: "Greedy" },
      { tag: "Queue" },
    ],
  },
  {
    id: 29,
    title: "Delete the Middle Node of a Linked List",
    href: "https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Linked List" },
      { tag: "Two Pointers" },
    ],
  },
  {
    id: 30,
    title: "Odd Even Linked List",
    href: "https://leetcode.com/problems/odd-even-linked-list/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Linked List" },
    ],
  },
  {
    id: 31,
    title: "Reverse Linked List",
    href: "https://leetcode.com/problems/reverse-linked-list/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Linked List" },
      { tag: "Recursion" },
    ],
  },
  {
    id: 32,
    title: "Maximum Twin Sum of a Linked List",
    href: "https://leetcode.com/problems/maximum-twin-sum-of-a-linked-list/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Linked List" },
      { tag: "Two Pointers" },
      { tag: "Stack" },
    ],
  },
  {
    id: 33,
    title: "Maximum Depth of Binary Tree",
    href: "https://leetcode.com/problems/maximum-depth-of-binary-tree/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Binary Tree" },
    ],
  },
  {
    id: 34,
    title: "Leaf-Similar Trees",
    href: "https://leetcode.com/problems/leaf-similar-trees/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Binary Tree" },
    ],
  },
  {
    id: 35,
    title: "Count Good Nodes in Binary Tree",
    href: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Binary Tree" },
    ],
  },
  {
    id: 36,
    title: "Path Sum III",
    href: "https://leetcode.com/problems/path-sum-iii/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Binary Tree" },
    ],
  },
  {
    id: 37,
    title: "Longest ZigZag Path in a Binary Tree",
    href: "https://leetcode.com/problems/longest-zigzag-path-in-a-binary-tree/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Dynamic Programming" },
      { tag: "Depth-First Search" },
      { tag: "Binary Tree" },
    ],
  },
  {
    id: 38,
    title: "Lowest Common Ancestor of a Binary Tree",
    href: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Binary Tree" },
    ],
  },
  {
    id: 39,
    title: "Binary Tree Right Side View",
    href: "https://leetcode.com/problems/binary-tree-right-side-view/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Binary Tree" },
    ],
  },
  {
    id: 40,
    title: "Maximum Level Sum of a Binary Tree",
    href: "https://leetcode.com/problems/maximum-level-sum-of-a-binary-tree/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Binary Tree" },
    ],
  },
  {
    id: 41,
    title: "Search in a Binary Search Tree",
    href: "https://leetcode.com/problems/search-in-a-binary-search-tree/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Binary Search Tree" },
      { tag: "Binary Tree" },
    ],
  },
  {
    id: 42,
    title: "Delete Node in a BST",
    href: "https://leetcode.com/problems/delete-node-in-a-bst/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Binary Search Tree" },
      { tag: "Binary Tree" },
    ],
  },
  {
    id: 43,
    title: "Keys and Rooms",
    href: "https://leetcode.com/problems/keys-and-rooms/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Graph" },
    ],
  },
  {
    id: 44,
    title: "Number of Provinces",
    href: "https://leetcode.com/problems/number-of-provinces/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Union Find" },
      { tag: "Graph" },
    ],
  },
  {
    id: 45,
    title: "Reorder Routes to Make All Paths Lead to the City Zero",
    href: "https://leetcode.com/problems/reorder-routes-to-make-all-paths-lead-to-the-city-zero/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Graph" },
    ],
  },
  {
    id: 46,
    title: "Evaluate Division",
    href: "https://leetcode.com/problems/evaluate-division/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Graph" },
    ],
  },
  {
    id: 47,
    title: "Nearest Exit from Entrance in Maze",
    href: "https://leetcode.com/problems/nearest-exit-from-entrance-in-maze/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Breadth-First Search" },
      { tag: "Matrix" },
    ],
  },
  {
    id: 48,
    title: "Rotting Oranges",
    href: "https://leetcode.com/problems/rotting-oranges/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Breadth-First Search" },
      { tag: "Matrix" },
    ],
  },
  {
    id: 49,
    title: "Kth Largest Element in an Array",
    href: "https://leetcode.com/problems/kth-largest-element-in-an-array/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Heap" },
      { tag: "Divide and Conquer" },
      { tag: "Sorting" },
    ],
  },
  {
    id: 50,
    title: "Smallest Number in Infinite Set",
    href: "https://leetcode.com/problems/smallest-number-in-infinite-set/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Hash Map" },
      { tag: "Design" },
      { tag: "Heap" },
    ],
  },
  {
    id: 51,
    title: "Maximum Subsequence Score",
    href: "https://leetcode.com/problems/maximum-subsequence-score/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Greedy" },
      { tag: "Sorting" },
      { tag: "Heap" },
    ],
  },
  {
    id: 52,
    title: "Total Cost to Hire K Workers",
    href: "https://leetcode.com/problems/total-cost-to-hire-k-workers/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Two Pointers" },
      { tag: "Heap" },
    ],
  },
  {
    id: 53,
    title: "Guess Number Higher or Lower",
    href: "https://leetcode.com/problems/guess-number-higher-or-lower/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Binary Search" },
      { tag: "Interactive" },
    ],
  },
  {
    id: 54,
    title: "Successful Pairs of Spells and Potions",
    href: "https://leetcode.com/problems/successful-pairs-of-spells-and-potions/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Two Pointers" },
      { tag: "Binary Search" },
      { tag: "Sorting" },
    ],
  },
  {
    id: 55,
    title: "Find Peak Element",
    href: "https://leetcode.com/problems/find-peak-element/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Binary Search" },
    ],
  },
  {
    id: 56,
    title: "Koko Eating Bananas",
    href: "https://leetcode.com/problems/koko-eating-bananas/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Binary Search" },
    ],
  },
  {
    id: 57,
    title: "Letter Combinations of a Phone Number",
    href: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Hash Map" },
      { tag: "String" },
      { tag: "Backtracking" },
    ],
  },
  {
    id: 58,
    title: "Combination Sum III",
    href: "https://leetcode.com/problems/combination-sum-iii/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Backtracking" },
    ],
  },
  {
    id: 59,
    title: "N-th Tribonacci Number",
    href: "https://leetcode.com/problems/n-th-tribonacci-number/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Math" },
      { tag: "Dynamic Programming" },
      { tag: "Memoization" },
    ],
  },
  {
    id: 60,
    title: "Min Cost Climbing Stairs",
    href: "https://leetcode.com/problems/min-cost-climbing-stairs/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Dynamic Programming" },
    ],
  },
  {
    id: 61,
    title: "House Robber",
    href: "https://leetcode.com/problems/house-robber/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Dynamic Programming" },
    ],
  },
  {
    id: 62,
    title: "Domino and Tromino Tiling",
    href: "https://leetcode.com/problems/domino-and-tromino-tiling/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Dynamic Programming" },
    ],
  },
  {
    id: 63,
    title: "Unique Paths",
    href: "https://leetcode.com/problems/unique-paths/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Math" },
      { tag: "Dynamic Programming" },
      { tag: "Combinatorics" },
    ],
  },
  {
    id: 64,
    title: "Longest Common Subsequence",
    href: "https://leetcode.com/problems/longest-common-subsequence/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "String" },
      { tag: "Dynamic Programming" },
    ],
  },
  {
    id: 65,
    title: "Best Time to Buy and Sell Stock with Transaction Fee",
    href: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Dynamic Programming" },
      { tag: "Greedy" },
    ],
  },
  {
    id: 66,
    title: "Edit Distance",
    href: "https://leetcode.com/problems/edit-distance/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "String" },
      { tag: "Dynamic Programming" },
    ],
  },
  {
    id: 67,
    title: "Counting Bits",
    href: "https://leetcode.com/problems/counting-bits/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Dynamic Programming" },
      { tag: "Bit Manipulation" },
    ],
  },
  {
    id: 68,
    title: "Single Number",
    href: "https://leetcode.com/problems/single-number/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Bit Manipulation" },
    ],
  },
  {
    id: 69,
    title: "Minimum Flips to Make a OR b Equal to c",
    href: "https://leetcode.com/problems/minimum-flips-to-make-a-or-b-equal-to-c/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Bit Manipulation" },
    ],
  },
  {
    id: 70,
    title: "Implement Trie (Prefix Tree)",
    href: "https://leetcode.com/problems/implement-trie-prefix-tree/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Hash Map" },
      { tag: "String" },
      { tag: "Design" },
      { tag: "Trie" },
    ],
  },
  {
    id: 71,
    title: "Search Suggestions System",
    href: "https://leetcode.com/problems/search-suggestions-system/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Heap" },
      { tag: "String" },
      { tag: "Binary Search" },
      { tag: "Trie" },
    ],
  },
  {
    id: 72,
    title: "Non-overlapping Intervals",
    href: "https://leetcode.com/problems/non-overlapping-intervals/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Dynamic Programming" },
      { tag: "Greedy" },
      { tag: "Sorting" },
    ],
  },
  {
    id: 73,
    title: "Minimum Number of Arrows to Burst Balloons",
    href: "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Greedy" },
      { tag: "Sorting" },
    ],
  },
  {
    id: 74,
    title: "Daily Temperatures",
    href: "https://leetcode.com/problems/daily-temperatures/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Stack" },
      { tag: "Monotonic Stack" },
    ],
  },
  {
    id: 75,
    title: "Online Stock Span",
    href: "https://leetcode.com/problems/online-stock-span/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Stack" },
      { tag: "Design" },
      { tag: "Monotonic Stack" },
    ],
  },
  // 75 problems end here ^^^

  {
    id: 76,
    title: "Contains Duplicate",
    href: "https://leetcode.com/problems/contains-duplicate/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Map" },
      { tag: "Sorting" },
    ],
  },
  {
    id: 77,
    title: "Valid Anagram",
    href: "https://leetcode.com/problems/valid-anagram/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Hash Map" },
      { tag: "String" },
      { tag: "Sorting" },
    ],
  },
  {
    id: 78,
    title: "Two Sum",
    href: "https://leetcode.com/problems/two-sum/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Map" },
    ],
  },
  {
    id: 79,
    title: "Group Anagrams",
    href: "https://leetcode.com/problems/group-anagrams/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Map" },
      { tag: "String" },
      { tag: "Sorting" },
    ],
  },
  {
    id: 80,
    title: "Top K Frequent Elements",
    href: "https://leetcode.com/problems/top-k-frequent-elements/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Map" },
      { tag: "Heap" },
      { tag: "Sorting" },
    ],
  },
  {
    id: 81,
    title: "Encode and Decode Strings",
    href: "https://leetcode.com/problems/encode-and-decode-strings/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Design" },
      { tag: "String" },
    ],
  },
  {
    id: 82,
    title: "Longest Consecutive Sequence",
    href: "https://leetcode.com/problems/longest-consecutive-sequence/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Map" },
      { tag: "Union Find" },
    ],
  },
  {
    id: 83,
    title: "Valid Palindrome",
    href: "https://leetcode.com/problems/valid-palindrome/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Two Pointers" },
      { tag: "String" },
    ],
  },
  {
    id: 84,
    title: "3Sum",
    href: "https://leetcode.com/problems/3sum/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Two Pointers" },
      { tag: "Sorting" },
    ],
  },
  {
    id: 85,
    title: "Best Time to Buy And Sell Stock",
    href: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Dynamic Programming" },
    ],
  },
  {
    id: 86,
    title: "Longest Substring Without Repeating Characters",
    href: "https://leetcode.com/problems/longest-substring-without-repeating-characters/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Hash Map" },
      { tag: "String" },
      { tag: "Sliding Window" },
    ],
  },
  {
    id: 87,
    title: "Longest Repeating Character Replacement",
    href: "https://leetcode.com/problems/longest-repeating-character-replacement/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Hash Map" },
      { tag: "String" },
      { tag: "Sliding Window" },
    ],
  },
  {
    id: 88,
    title: "Minimum Window Substring",
    href: "https://leetcode.com/problems/minimum-window-substring/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "Hash Map" },
      { tag: "String" },
      { tag: "Sliding Window" },
    ],
  },
  {
    id: 89,
    title: "Valid Parentheses",
    href: "https://leetcode.com/problems/valid-parentheses/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "String" },
      { tag: "Stack" },
    ],
  },
  {
    id: 90,
    title: "Find Minimum in Rotated Sorted Array",
    href: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Binary Search" },
    ],
  },
  {
    id: 91,
    title: "Search in Rotated Sorted Array",
    href: "https://leetcode.com/problems/search-in-rotated-sorted-array/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Binary Search" },
    ],
  },
  {
    id: 92,
    title: "Merge Two Sorted Lists",
    href: "https://leetcode.com/problems/merge-two-sorted-lists/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Linked List" },
      { tag: "Recursion" },
    ],
  },
  {
    id: 93,
    title: "Linked List Cycle",
    href: "https://leetcode.com/problems/linked-list-cycle/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Linked List" },
      { tag: "Two Pointers" },
      { tag: "Fast & Slow Pointers"}
    ],
  },
  {
    id: 94,
    title: "Reorder List",
    href: "https://leetcode.com/problems/reorder-list/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Linked List" },
      { tag: "Two Pointers" },
      { tag: "Fast & Slow Pointers" },
    ],
  },
  {
    id: 95,
    title: "Remove Nth Node From End of List",
    href: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Linked List" },
      { tag: "Two Pointers" },
    ],
  },
  {
    id: 96,
    title: "Merge k Sorted Lists",
    href: "https://leetcode.com/problems/merge-k-sorted-lists/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "Linked List" },
      { tag: "Heap" },
      { tag: "Merge Sort" },
    ],
  },
  {
    id: 97,
    title: "Invert Binary Tree",
    href: "https://leetcode.com/problems/invert-binary-tree/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Binary Tree" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
    ],
  },
  {
    id: 99,
    title: "Same Tree",
    href: "https://leetcode.com/problems/same-tree/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Binary Tree" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
    ],
  },
  {
    id: 100,
    title: "Subtree of Another Tree",
    href: "https://leetcode.com/problems/subtree-of-another-tree/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Binary Tree" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
    ],
  },
  {
    id: 101,
    title: "Lowest Common Ancestor of a Binary Search Tree",
    href: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Binary Search Tree" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
    ],
  },
  {
    id: 102,
    title: "Binary Tree Level Order Traversal",
    href: "https://leetcode.com/problems/binary-tree-level-order-traversal/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Binary Tree" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
    ],
  },
  {
    id: 103,
    title: "Validate Binary Search Tree",
    href: "https://leetcode.com/problems/validate-binary-search-tree/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Binary Search Tree" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
    ],
  },
  {
    id: 104,
    title: "Kth Smallest Element in a BST",
    href: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Binary Search Tree" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
    ],
  },
  {
    id: 105,
    title: "Construct Binary Tree from Preorder and Inorder Traversal",
    href: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Binary Tree" },
      { tag: "Hash Map" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
    ],
  },
  {
    id: 106,
    title: "Binary Tree Maxiumum Path Sum",
    href: "https://leetcode.com/problems/binary-tree-maximum-path-sum/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "Binary Tree" },
      { tag: "Depth-First Search" },
      { tag: "Dynamic Programming" },
    ],
  },
  {
    id: 107,
    title: "Serialize and Deserialize Binary Tree",
    href: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "Binary Tree" },
      { tag: "String" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
    ],
  },
  {
    id: 108,
    title: "Find Median from Data Stream",
    href: "https://leetcode.com/problems/find-median-from-data-stream/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "Heap" },
      { tag: "Sorting" },
      { tag: "Two Pointers" },
      { tag: "Two-Heaps Pattern" },
    ],
  },
  {
    id: 109,
    title: "Combination Sum",
    href: "https://leetcode.com/problems/combination-sum/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Backtracking" },
    ],
  }, 
  {
    id: 110,
    title: "Word Search",
    href: "https://leetcode.com/problems/word-search/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "String" },
      { tag: "Backtracking" },
      { tag: "Matrix" },
    ],
  }, 
  {
    id: 112,
    title: "Design Add and Search Words Data Structure",
    href: "https://leetcode.com/problems/design-add-and-search-words-data-structure/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "String" },
      { tag: "Depth-First Search" },
      { tag: "Trie" },
    ],
  }, 
  {
    id: 113,
    title: "Word Search II",
    href: "https://leetcode.com/problems/word-search-ii/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "String" },
      { tag: "Backtracking" },
      { tag: "Trie" },
      { tag: "Matrix" },
    ],
  }, 
  {
    id: 114,
    title: "Number of Islands",
    href: "https://leetcode.com/problems/number-of-islands/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Matrix" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
    ],
  }, 
  {
    id: 115,
    title: "Clone Graph",
    href: "https://leetcode.com/problems/clone-graph/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Hash Map" },
      { tag: "Graph" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
    ],
  }, 
  {
    id: 116,
    title: "Pacific Atlantic Water Flow",
    href: "https://leetcode.com/problems/pacific-atlantic-water-flow/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Matrix" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
    ],
  }, 
  {
    id: 117,
    title: "Course Schedule",
    href: "https://leetcode.com/problems/cource-schedule/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Graph" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Topological Sort" },
    ],
  }, 
  {
    id: 118,
    title: "Graph Valid Tree",
    href: "https://leetcode.com/problems/graph-valid-tree/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Graph" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Union Find" },
    ],
  }, 
  {
    id: 119,
    title: "Number of Connected Components in an Undirected Graph",
    href: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Graph" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Union Find" },
    ],
  }, 
  {
    id: 120,
    title: "Alien Dictionary",
    href: "https://leetcode.com/problems/alien-dictionary/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "Graph" },
      { tag: "Depth-First Search" },
      { tag: "Breadth-First Search" },
      { tag: "Topological Sort" },
    ],
  }, 
  {
    id: 121,
    title: "Climbing Stairs",
    href: "https://leetcode.com/problems/climbing-stairs/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Math" },
      { tag: "Dynamic Programming" },
    ],
  }, 
  {
    id: 123,
    title: "House Robber II",
    href: "https://leetcode.com/problems/house-robber-ii/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Dynamic Programming" },
    ],
  },
  {
    id: 124,
    title: "Longest Palindromic Substring",
    href: "https://leetcode.com/problems/longest-palindromic-substring/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Two Pointers" },
      { tag: "String"},
      { tag: "Dynamic Programming" },
    ],
  },
  {
    id: 125,
    title: "Palindromic Substrings",
    href: "https://leetcode.com/problems/palindromic-substrings/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Two Pointers" },
      { tag: "String"},
      { tag: "Dynamic Programming" },
    ],
  },
  {
    id: 126,
    title: "Decode Ways",
    href: "https://leetcode.com/problems/decode-ways/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "String"},
      { tag: "Dynamic Programming" },
    ],
  },
  {
    id: 127,
    title: "Coin Change",
    href: "https://leetcode.com/problems/coin-change/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Dynamic Programming" },
      { tag: "Breadth-First Search"},
    ],
  },
  {
    id: 128,
    title: "Maximum Product Subarray",
    href: "https://leetcode.com/problems/maximum-product-subarray/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Dynamic Programming" },
    ],
  },
  {
    id: 129,
    title: "Word Break",
    href: "https://leetcode.com/problems/word-break/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "String"},
      { tag: "Dynamic Programming" },
    ],
  },
  {
    id: 130,
    title: "Longest Increasing Subsequence",
    href: "https://leetcode.com/problems/longest-increasing-subsequence/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Binary Search"},
      { tag: "Dynamic Programming" },
    ],
  },
  {
    id: 133,
    title: "Maximum Subarray",
    href: "https://leetcode.com/problems/maximum-subarray/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Greedy"},
      { tag: "Dynamic Programming" },
    ],
  },
  {
    id: 134,
    title: "Jump Game",
    href: "https://leetcode.com/problems/jump-game/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Greedy"},
      { tag: "Dynamic Programming" },
    ],
  },
  {
    id: 135,
    title: "Meeting Rooms",
    href: "https://leetcode.com/problems/meeting-rooms/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Sorting"},
      { tag: "Intervals"},
    ],
  },
  {
    id: 136,
    title: "Meeting Rooms II",
    href: "https://leetcode.com/problems/meeting-rooms-ii/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Heap"},
      { tag: "Sorting"},
      { tag: "Intervals"},
    ],
  },
  {
    id: 137,
    title: "Insert Interval",
    href: "https://leetcode.com/problems/insert-interval/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Intervals"},
    ],
  },
  {
    id: 138,
    title: "Merge Intervals",
    href: "https://leetcode.com/problems/merge-intervals/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Sorting"},
      { tag: "Intervals"},
    ],
  },
  {
    id: 140,
    title: "Rotate Image",
    href: "https://leetcode.com/problems/rotate-image/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Math"},
      { tag: "Matrix"},
    ],
  },
  {
    id: 141,
    title: "Spiral Matrix",
    href: "https://leetcode.com/problems/spiral-matrix/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Math"},
      { tag: "Matrix"},
    ],
  },
  {
    id: 142,
    title: "Set Matrix Zeroes",
    href: "https://leetcode.com/problems/set-matrix-zeroes/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array" },
      { tag: "Hash Map"},
      { tag: "Matrix"},
    ],
  },
  {
    id: 143,
    title: "Number of 1 Bits",
    href: "https://leetcode.com/problems/number-of-1-bits/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Math"},
      { tag: "Bit Manipulation" },
    ],
  },
  {
    id: 145,
    title: "Reverse Bits",
    href: "https://leetcode.com/problems/reverse-bits/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Math"},
      { tag: "Bit Manipulation" },
    ],
  },
  {
    id: 146,
    title: "Missing Number",
    href: "https://leetcode.com/problems/missing-number/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Math"},
      { tag: "Bit Manipulation" },
    ],
  },
  {
    id: 147,
    title: "Sum of Two Integers",
    href: "https://leetcode.com/problems/sum-of-two-integers/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Math"},
      { tag: "Bit Manipulation" },
    ],
  },
  {
    id: 148,
    title: "Valid Sudoku",
    href: "https://leetcode.com/problems/valid-sudoku/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Hash Map" },
      { tag: "Matrix" },
    ],
  },
  {
    id: 149,
    title: "Two Sum II - Input Array Is Sorted",
    href: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Two Pointers" },
      { tag: "Binary Search" },
    ],
  },
  {
    id: 150,
    title: "Trapping Rain Water",
    href: "https://leetcode.com/problems/trapping-rain-water/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Two Pointers" },
    ],
  },
  {
    id: 151,
    title: "Permutation in String",
    href: "https://leetcode.com/problems/permutation-in-string/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "String"},
      { tag: "Sliding Window" },
      { tag: "Hash Map" },
    ],
  },
  {
    id: 152,
    title: "Sliding Window Maximum",
    href: "https://leetcode.com/problems/sliding-window-maximum/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Sliding Window" },
      { tag: "Queue" },
    ],
  },
  {
    id: 153,
    title: "Min Stack",
    href: "https://leetcode.com/problems/min-stack/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Stack" },
    ],
  }, 
  {
    id: 154,
    title: "Evaluate Reverse Polish Notation",
    href: "https://leetcode.com/problems/evaluate-reverse-polish-notation/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Math" },
      { tag: "Stack" },
    ],
  }, 
  {
    id: 155,
    title: "Generate Parentheses",
    href: "https://leetcode.com/problems/generate-parentheses/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "String"},
      { tag: "Backtracking" },
    ],
  }, 
  {
    id: 157,
    title: "Car Fleet",
    href: "https://leetcode.com/problems/car-fleet/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Stack" },
      { tag: "Sorting" },
    ],
  }, 
  {
    id: 158,
    title: "Largest Rectangle in Histogram",
    href: "https://leetcode.com/problems/largest-rectangle-in-histogram/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Stack" },
    ],
  }, 
  {
    id: 159,
    title: "Binary Search",
    href: "https://leetcode.com/problems/binary-search/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Binary Search" },
    ],
  }, 
  {
    id: 160,
    title: "Time Based Key-Value Store",
    href: "https://leetcode.com/problems/time-based-key-value-store/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "String" },
      { tag: "Binary Search"},
      { tag: "Hash Map"},
    ],
  },
  {
    id: 161,
    title: "Search a 2D Matrix",
    href: "https://leetcode.com/problems/search-a-2d-matrix/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Binary Search" },
      { tag: "Matrix"},
    ],
  },
  {
    id: 162,
    title: "Median of Two Sorted Arrays",
    href: "https://leetcode.com/problems/median-of-two-sorted-arrays/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Binary Search" },
    ],
  },
  {
    id: 163,
    title: "Copy List with Random Pointer",
    href: "https://leetcode.com/problems/copy-list-with-random-pointer/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Hash Map"},
      { tag: "Linked List" },
    ],
  },
  {
    id: 164,
    title: "Add Two Numbers",
    href: "https://leetcode.com/problems/add-two-numbers/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Math"},
      { tag: "Linked List"},
      { tag: "Recursion" },
    ],
  },
  {
    id: 165,
    title: "Find the Duplicate Number",
    href: "https://leetcode.com/problems/find-the-duplicate-number/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Fast & Slow Pointers" },
      { tag: "Binary Search"},
    ],
  },
  {
    id: 166,
    title: "LRU Cache",
    href: "https://leetcode.com/problems/lru-cache/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Hash Map"},
      { tag: "Linked List" },
      { tag: "Design"},
    ],
  },
  {
    id: 167,
    title: "Reverse Nodes in k-Group",
    href: "https://leetcode.com/problems/reverse-nodes-in-k-group/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "Linked List"},
      { tag: "Two Pointers"},
      { tag: "Recursion" },
    ],
  },
  {
    id: 168,
    title: "Diameter of Binary Tree",
    href: "https://leetcode.com/problems/diameter-of-binary-tree/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Binary Tree"},
      { tag: "Depth-First Search"},
    ],
  },
  {
    id: 169,
    title: "Balanced Binary Tree",
    href: "https://leetcode.com/problems/balanced-binary-tree/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Binary Tree"},
      { tag: "Depth-First Search"},
    ],
  },
  {
    id: 170,
    title: "Kth Largest Element in a Stream",
    href: "https://leetcode.com/problems/kth-largest-element-in-a-stream/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Binary Search Tree"},
      { tag: "Heap"},
      { tag: "Design"}
    ],
  },
  {
    id: 171,
    title: "Last Stone Weight",
    href: "https://leetcode.com/problems/last-stone-weight/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Heap"},
    ],
  },
  {
    id: 172,
    title: "K Closest Points to Origin",
    href: "https://leetcode.com/problems/k-closest-points-to-origin/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Math"},
      { tag: "Array"},
      { tag: "Heap"},
    ],
  },
  {
    id: 173,
    title: "Task Scheduler",
    href: "https://leetcode.com/problems/task-scheduler/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Heap"},
      { tag: "Sorting"}
    ],
  },
  {
    id: 174,
    title: "Design Twitter",
    href: "https://leetcode.com/problems/design-twitter/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Hash Map"},
      { tag: "Heap"},
    ],
  },
  {
    id: 175,
    title: "Subsets",
    href: "https://leetcode.com/problems/subsets/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Backtracking"},
    ],
  },
  {
    id: 176,
    title: "Permutations",
    href: "https://leetcode.com/problems/permutations/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Backtracking"},
    ],
  },
  {
    id: 177,
    title: "Subsets II",
    href: "https://leetcode.com/problems/subsets-ii/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Backtracking"},
    ],
  },
  {
    id: 178,
    title: "Palindrome Partitioning",
    href: "https://leetcode.com/problems/palindrome-partitioning/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "String"},
      { tag: "Array"},
      { tag: "Backtracking"},
    ],
  },
  {
    id: 179,
    title: "N-Queens",
    href: "https://leetcode.com/problems/n-queens/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Backtracking"},
    ],
  },
  {
    id: 180,
    title: "Max Area of Island",
    href: "https://leetcode.com/problems/max-area-of-island/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Matrix"},
      { tag: "Depth-First Search"},
      { tag: "Breadth-First Search"},
    ],
  },
  {
    id: 181,
    title: "Walls and Gates",
    href: "https://leetcode.com/problems/walls-and-gates/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Matrix"},
      { tag: "Breadth-First Search"},
    ],
  },
  {
    id: 182,
    title: "Surrounded Regions",
    href: "https://leetcode.com/problems/surrounded-regions/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Matrix"},
      { tag: "Depth-First Search"},
      { tag: "Breadth-First Search"},
    ],
  },
  {
    id: 183,
    title: "Course Schedule II",
    href: "https://leetcode.com/problems/course-schedule-ii/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Graph"},
      { tag: "Depth-First Search"},
      { tag: "Breadth-First Search"},
      { tag: "Topological Sort"},
    ],
  },
  {
    id: 184,
    title: "Redundant Connection",
    href: "https://leetcode.com/problems/redundant-connection/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Graph"},
      { tag: "Depth-First Search"},
      { tag: "Breadth-First Search"},
      { tag: "Union Find"}
    ],
  },
  {
    id: 185,
    title: "Word Ladder",
    href: "https://leetcode.com/problems/word-ladder/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "String"},
      { tag: "Hash Map"},
      { tag: "Breadth-First Search"},
    ],
  },
  {
    id: 186,
    title: "Min Cost to Connect All Points",
    href: "https://leetcode.com/problems/min-costs-to-connect-all-points/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Graph"},
      { tag: "Union Find"},
      { tag: "Minimum Spanning Tree"},
    ],
  },
  {
    id: 187,
    title: "Network Delay Time",
    href: "https://leetcode.com/problems/network-delay-time/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Heap"},
      { tag: "Graph"},
      { tag: "Depth-First Search"},
      { tag: "Breadth-First Search"},
    ],
  },
  {
    id: 188,
    title: "Cheapest Flights Within K Stops",
    href: "https://leetcode.com/problems/cheapest-flights-within-k-stops/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Heap"},
      { tag: "Graph"},
      { tag: "Depth-First Search"},
      { tag: "Breadth-First Search"},
    ],
  },
  {
    id: 189,
    title: "Reconstruct Itinerary",
    href: "https://leetcode.com/problems/reconstruct-itinerary/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "Graph"},
      { tag: "Depth-First Search"},
      { tag: "Breadth-First Search"},
    ],
  },
  {
    id: 190,
    title: "Swim in Rising Water",
    href: "https://leetcode.com/problems/swim-in-rising-water/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "Binary Search"},
      { tag: "Matrix"},
      { tag: "Depth-First Search"},
      { tag: "Breadth-First Search"},
    ],
  },
  {
    id: 191,
    title: "Partition Equal Subset Sum",
    href: "https://leetcode.com/problems/partition-equal-subset-sum/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Dynamic Programming"},
    ],
  },
  {
    id: 192,
    title: "Best Time to Buy and Sell Stock with Cooldown",
    href: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Dynamic Programming"},
    ],
  },
  {
    id: 193,
    title: "Coin Change II",
    href: "https://leetcode.com/problems/coin-change-ii/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Dynamic Programming"},
    ],
  },
  {
    id: 194,
    title: "Target Sum",
    href: "https://leetcode.com/problems/target-sum/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Backtracking"},
      { tag: "Dynamic Programming"},
    ],
  },
  {
    id: 195,
    title: "Interleaving String",
    href: "https://leetcode.com/problems/interleaving-string/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "String"},
      { tag: "Dynamic Programming"},
    ],
  },
  {
    id: 196,
    title: "Longest Increasing Path in a Matrix",
    href: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "Matrix"},
      { tag: "Dynamic Programming"},
      { tag: "Depth-First Search"},
      { tag: "Breadth-First Search"},
    ],
  },
  {
    id: 197,
    title: "Distinct Subsequences",
    href: "https://leetcode.com/problems/distinct-subsequences/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "String"},
      { tag: "Dynamic Programming"},
    ],
  },
  {
    id: 198,
    title: "Burst Balloons",
    href: "https://leetcode.com/problems/burst-balloons/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Dynamic Programming"},
    ],
  },
  {
    id: 199,
    title: "Regular Expression Matching",
    href: "https://leetcode.com/problems/regular-expression-matching/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "String"},
      { tag: "Dynamic Programming"},
      { tag: "Recursion"}
    ],
  },
  {
    id: 200,
    title: "Jump Game II",
    href: "https://leetcode.com/problems/jump-game-ii/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Greedy"},
      { tag: "Dynamic Programming"},
    ],
  },
  {
    id: 201,
    title: "Gas Station",
    href: "https://leetcode.com/problems/gas-station/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Greedy"},
    ],
  },
  {
    id: 202,
    title: "Hand of Straights",
    href: "https://leetcode.com/problems/hand-of-straights/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Hash Map"},
      { tag: "Greedy"},
      { tag: "Sorting"},
    ],
  },
  {
    id: 203,
    title: "Merge Triplets to Form Target Triplet",
    href: "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Greedy"},
    ],
  },
  {
    id: 204,
    title: "Partition Labels",
    href: "https://leetcode.com/problems/partition-labels/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "String"},
      { tag: "Two Pointers"},
      { tag: "Hash Map"},
      { tag: "Greedy"},
    ],
  },
  {
    id: 205,
    title: "Valid Parentheses String",
    href: "https://leetcode.com/problems/valid-parentheses-string/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "String"},
      { tag: "Greedy"},
      { tag: "Dynamic Programming"},
    ],
  },
  {
    id: 206,
    title: "Minimum Interval to Include Each Query",
    href: "https://leetcode.com/problems/minimum-interval-to-include-each-query/description",
    difficulty: "Hard",
    videoURL: "",
    tags: [
      { tag: "Array"},
      { tag: "Heap"},
      { tag: "Binary Search"},
      { tag: "Interval"},
    ],
  },
  {
    id: 207,
    title: "Happy Number",
    href: "https://leetcode.com/problems/happy-number/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Math"},
      { tag: "Hash Map"},
      { tag: "Two Pointers"},
    ],
  },
  {
    id: 208,
    title: "Plus One",
    href: "https://leetcode.com/problems/plus-one/description",
    difficulty: "Easy",
    videoURL: "",
    tags: [
      { tag: "Math"},
      { tag: "Array"},
    ],
  },
  {
    id: 209,
    title: "Pow(x, n)",
    href: "https://leetcode.com/problems/powx-n/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Math"},
      { tag: "Recursion"},
    ],
  },
  {
    id: 210,
    title: "Multiply Strings",
    href: "https://leetcode.com/problems/multiply-strings/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Math"},
      { tag: "String"},
    ],
  },
  {
    id: 211,
    title: "Detect Squares",
    href: "https://leetcode.com/problems/detect-squares/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Math"},
      { tag: "Array"},
      { tag: "Hash Map"},
    ],
  },
  {
    id: 212,
    title: "Reverse Integer",
    href: "https://leetcode.com/problems/reverse-integer/description",
    difficulty: "Medium",
    videoURL: "",
    tags: [
      { tag: "Math"},
      { tag: "Bit Manipulation"},
    ],
  },
];

async function seedLeetCodeProblems() {
  await database.leetCodeProblem.deleteMany({});
  await database.problemTag.deleteMany({});

  for (const problem of leetCodeProblems) {
    const tags = problem.tags.map(tag => ({
      where: { tag: tag.tag },
      create: { tag: tag.tag },
    }));

    await database.leetCodeProblem.create({
      data: {
        id: problem.id,
        title: problem.title,
        href: problem.href,
        difficulty: problem.difficulty,
        videoURL: problem.videoURL,
        tags: {
          connectOrCreate: tags,
        },
      },
    });
  }

  console.log(`${leetCodeProblems.length} LeetCode problems have been inserted.`);
}

seedLeetCodeProblems()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await database.$disconnect();
  });

